#!/bin/bash

echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║                                                                  ║"
echo "║        VAR CHARTS STORAGE & RESULTS MIGRATION                    ║"
echo "║                                                                  ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""

echo "This script will:"
echo "  1. Create Supabase Storage bucket for VaR charts"
echo "  2. Enhance results table with new columns"
echo "  3. Create indexes for efficient history queries"
echo "  4. Set up RLS policies for secure access"
echo ""

SUPABASE_URL="https://qlyqxlzlxdqboxpxpdjp.supabase.co"
SUPABASE_SERVICE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFseXF4bHpseGRxYm94cHhwZGpwIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MDExOTA3MywiZXhwIjoyMDY1Njk1MDczfQ.Q5DzOuNAUu9591plbbtITiCfHulbg4-YwS0uBvimuk"

echo "═══════════════════════════════════════════════════════════════"
echo "STEP 1: Apply Results Table Migration"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Please run this SQL in your Supabase SQL Editor:"
echo "https://supabase.com/dashboard/project/qlyqxlzlxdqboxpxpdjp/sql"
echo ""
echo "---START SQL---"
cat supabase/migrations/20250928000005_enhance_results_table.sql
echo "---END SQL---"
echo ""
read -p "Press Enter after running the migration SQL..."

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "STEP 2: Create Storage Bucket"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Creating var-charts bucket in Supabase Storage..."
echo ""
echo "Option 1: Use Supabase Dashboard (Recommended)"
echo "  1. Go to: https://supabase.com/dashboard/project/qlyqxlzlxdqboxpxpdjp/storage/buckets"
echo "  2. Click 'New bucket'"
echo "  3. Name: var-charts"
echo "  4. Make it public: ✓"
echo "  5. Click 'Create bucket'"
echo ""
echo "Option 2: Run SQL"
echo "  Run this in SQL Editor:"
echo ""
cat supabase/create-var-charts-bucket.sql
echo ""
read -p "Press Enter after creating the storage bucket..."

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "MIGRATION COMPLETE!"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "✅ Results table enhanced"
echo "✅ Storage bucket created"
echo "✅ Ready to save VaR results and charts"
echo ""
echo "Next steps:"
echo "  1. Redeploy backend to Railway with updated code"
echo "  2. Rebuild mobile app with new sync code"
echo "  3. Run VaR analysis and verify:"
echo "     - Charts display immediately (base64)"
echo "     - Charts uploaded to Supabase Storage"
echo "     - Results saved to database"
echo "     - History shows last 5 analyses"
echo ""

