#!/bin/bash
# One-time migration script to sync existing portfolios to Supabase

echo "🔄 Portfolio Migration to Supabase"
echo "==================================="
echo ""
echo "This script will help you migrate your existing portfolios"
echo "from AsyncStorage (local device storage) to Supabase."
echo ""
echo "📋 What this does:"
echo "  1. Reads all portfolios from your device's AsyncStorage"
echo "  2. Uploads them to Supabase database"
echo "  3. Creates portfolio and position records for VaR calculations"
echo ""
echo "⚠️  Note: This migration happens automatically now!"
echo "   - When you create a portfolio: Auto-synced ✅"
echo "   - When you update a portfolio: Auto-synced ✅"
echo "   - When you delete a portfolio: Auto-synced ✅"
echo ""
echo "🎯 To manually sync existing portfolios:"
echo "   1. Open your app"
echo "   2. Go to Settings or Portfolio screen"
echo "   3. Look for the 'Sync to Supabase' button"
echo "   4. Tap it to sync all portfolios"
echo ""
echo "🔍 To verify sync status:"
echo "   1. Open Supabase Dashboard:"
echo "      https://supabase.com/dashboard/project/qlyqxlzlxdqboxpxpdjp/editor"
echo "   2. Check 'portfolios' table - should show your portfolios"
echo "   3. Check 'positions' table - should show your assets"
echo ""
echo "✅ Once synced, VaR analysis will work with real data!"

